export const robots = [
  {
    id: 1,
    name: "Leanne Graham",
    username: "Bret",
    email: "Sincere@april.biz",
    active: true,
    address: {
      street: "Kulas Light",
      suite: "Apt. 556",
      city: "Gwenborough",
    },
  },
  {
    id: 2,
    name: "Ervin Howell",
    username: "Antonette",
    email: "Shanna@melissa.tv",
    active: true,
    address: {
      street: "Victor Plains",
      suite: "Suite 879",
      city: "Wisokyburgh",
    },
  },
  {
    id: 3,
    name: "Clementine Bauch",
    username: "Samantha",
    email: "Nathan@yesenia.net",
    active: false,
    address: {
      street: "Douglas Extension",
      suite: "Suite 847",
      city: "McKenziehaven",
    },
  },
  {
    id: 4,
    name: "Patricia Lebsack",
    username: "Karianne",
    email: "Julianne.OConner@kory.org",
    active: true,
    address: {
      street: "Hoeger Mall",
      suite: "Apt. 692",
      city: "South Elvis",
    },
  },
  {
    id: 5,
    name: "Chelsey Dietrich",
    username: "Kamren",
    email: "Lucio_Hettinger@annie.ca",
    active: true,
    address: {
      street: "Skiles Walks",
      suite: "Suite 351",
      city: "Roscoeview",
    },
  },
  {
    id: 6,
    name: "Mrs. Dennis Schulist",
    username: "Leopoldo_Corkery",
    email: "Karley_Dach@jasper.info",
    active: true,
    address: {
      street: "Norberto Crossing",
      suite: "Apt. 950",
      city: "South Christy",
    },
  },
  {
    id: 7,
    name: "Kurtis Weissnat",
    username: "Elwyn.Skiles",
    email: "Telly.Hoeger@billy.biz",
    active: true,
    address: {
      street: "Rex Trail",
      suite: "Suite 280",
      city: "Howemouth",
    },
  },
  {
    id: 8,
    name: "Nicholas Runolfsdottir V",
    username: "Maxime_Nienow",
    email: "Sherwood@rosamond.me",
    active: false,
    address: {
      street: "Ellsworth Summit",
      suite: "Suite 729",
      city: "Aliyaview",
    },
  },
  {
    id: 9,
    name: "Glenna Reichert",
    username: "Delphine",
    email: "Chaim_McDermott@dana.io",
    active: true,
    address: {
      street: "Dayna Park",
      suite: "Suite 449",
      city: "Bartholomebury",
    },
  },
  {
    id: 10,
    name: "Clementina DuBuque",
    username: "Moriah.Stanton",
    email: "Rey.Padberg@karina.biz",
    active: true,
    address: {
      street: "Kattie Turnpike",
      suite: "Suite 198",
      city: "Lebsackbury",
    },
  },
];
